# Generated by Django 3.2.9 on 2021-12-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('text', models.TextField(max_length=500, verbose_name='Matn qismi')),
                ('image', models.ImageField(upload_to='tasks/', verbose_name='surat')),
            ],
            options={
                'verbose_name': 'Qayd',
                'verbose_name_plural': 'Qaydlar',
            },
        ),
    ]
