# Generated by Django 3.2.9 on 2021-12-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('fikr', models.TextField(max_length=200)),
                ('kasb', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='fikrlar/', verbose_name='surat')),
            ],
            options={
                'verbose_name': 'Fikr',
                'verbose_name_plural': 'Fikrlar',
            },
        ),
    ]
