# Generated by Django 3.2.9 on 2021-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='rasm')),
                ('name', models.CharField(max_length=20, verbose_name='surat nomi')),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'Suratlar',
            },
        ),
    ]
